<?php
/**
 * RocketWeb
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category  RocketWeb
 * @package   MageOS_NetSuiteConnector
 * @copyright Copyright (c) 2026 RocketWeb (http://rocketweb.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author    Rocket Web Inc.
 */

/** @var \MageOS\NetSuiteConnector\Order\Block\Adminhtml\Order\View\NetsuiteInfo $block */
?>
<?php if ($block->getNetsuiteInternalId()): ?>
    <section class="admin__page-section netsuite-order-info">
        <div class="admin__page-section-title">
            <span class="title"><?= __('NetSuite') ?></span>
        </div>
        <div class="admin__page-section-content">
            <p>
                <?= __('NetSuite Sales Order:') ?>
                <a href="<?= $block->getNetsuiteUrl() ?>" target="_blank"><?= $block->getNetsuiteInternalId() ?></a>
            </p>
        </div>
    </section>
<?php endif; ?>
